import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Lock, Sparkles, TrendingUp, Shield } from "lucide-react";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { loadStripe } from "@stripe/stripe-js";

interface ProUpgradeButtonProps {
  variant?: "default" | "outline" | "ghost";
}

export function ProUpgradeButton({ variant = "default" }: ProUpgradeButtonProps) {
  const [showDialog, setShowDialog] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleUpgrade = async () => {
    setIsLoading(true);
    try {
      const response = await apiRequest("POST", "/api/create-pro-checkout", {});
      const data = await response.json();

      if (data.mockMode) {
        toast({
          title: "Pro Access Unlocked! 🎉",
          description: data.message,
        });
        queryClient.invalidateQueries({ queryKey: ["/api/pro/status"] });
        setShowDialog(false);
      } else if (data.sessionId) {
        const publicKey = import.meta.env.VITE_STRIPE_PUBLIC_KEY;
        if (!publicKey) {
          throw new Error("Stripe public key not configured");
        }
        
        const stripe = await loadStripe(publicKey);
        if (!stripe) {
          throw new Error("Failed to load Stripe");
        }

        await stripe.redirectToCheckout({ sessionId: data.sessionId });
      }
    } catch (error: any) {
      toast({
        title: "Upgrade Failed",
        description: error.message || "Could not process upgrade",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <Button
        variant={variant}
        onClick={() => setShowDialog(true)}
        className="bg-gradient-to-r from-gray-800 to-black hover:from-gray-700 hover:to-gray-900 text-white border border-gray-600 shadow-lg transition-all duration-300 hover:scale-105"
        data-testid="button-upgrade-pro"
      >
        <Lock className="w-4 h-4 mr-2" />
        Upgrade to Pro
      </Button>

      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="bg-gradient-to-br from-gray-900 to-black text-white border border-gray-700">
          <DialogHeader>
            <DialogTitle className="text-2xl font-bold flex items-center gap-2">
              <Sparkles className="w-6 h-6 text-yellow-400" />
              KNEW Pro Access
            </DialogTitle>
            <DialogDescription className="text-gray-300">
              Unlock the full power of KNEW with Pro features
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-6 py-4">
            <div className="space-y-4">
              <div className="flex items-start gap-3 p-3 rounded-lg bg-gray-800/50 border border-gray-700 hover:border-gray-600 transition-all">
                <TrendingUp className="w-5 h-5 text-blue-400 mt-1" />
                <div>
                  <h4 className="font-semibold">AI Bias Detection</h4>
                  <p className="text-sm text-gray-400">
                    Get AI-powered bias analysis with confidence scores for every article
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-3 rounded-lg bg-gray-800/50 border border-gray-700 hover:border-gray-600 transition-all">
                <Shield className="w-5 h-5 text-green-400 mt-1" />
                <div>
                  <h4 className="font-semibold">Media Ownership Insights</h4>
                  <p className="text-sm text-gray-400">
                    See who owns the news with interactive ownership charts
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-3 rounded-lg bg-gray-800/50 border border-gray-700 hover:border-gray-600 transition-all">
                <Sparkles className="w-5 h-5 text-purple-400 mt-1" />
                <div>
                  <h4 className="font-semibold">Neutral AI Summaries</h4>
                  <p className="text-sm text-gray-400">
                    Get bias-free article summaries generated by AI
                  </p>
                </div>
              </div>
            </div>

            <div className="border-t border-gray-700 pt-4">
              <div className="flex items-baseline justify-center gap-2">
                <span className="text-4xl font-bold">$5</span>
                <span className="text-gray-400">one-time</span>
              </div>
              <p className="text-center text-sm text-gray-400 mt-2">
                Lifetime access to all Pro features
              </p>
            </div>

            <Button
              onClick={handleUpgrade}
              disabled={isLoading}
              className="w-full bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 text-white font-semibold py-6 text-lg transition-all duration-300 hover:scale-105"
              data-testid="button-confirm-upgrade"
            >
              {isLoading ? "Processing..." : "Unlock Pro Access Now"}
            </Button>

            <p className="text-xs text-center text-gray-500">
              Secure payment powered by Stripe. Cancel anytime.
            </p>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
